import {
  IdentityMismatch,
  type GenerationRequest,
  type GenerationResponse,
  type InferenceAdapter,
  type InferenceCapabilities,
} from './types';

const DISCLAIMER =
  'Example UI response — not generated by a released OpenVerifiableLLM model';

export class MockAdapter implements InferenceAdapter {
  private readonly forceWrongId: boolean;

  constructor(forceWrongId = false) {
    this.forceWrongId = forceWrongId;
  }

  async capabilities(): Promise<InferenceCapabilities> {
    return {
      mock: true,
      available: true,
      releaseIds: ['fixture-base'],
      modes: ['completion', 'conversation'],
      note: DISCLAIMER,
    };
  }

  async generate(request: GenerationRequest): Promise<GenerationResponse> {
    const releaseId = this.forceWrongId ? 'other-release' : request.releaseId;
    if (releaseId !== request.releaseId) {
      throw new IdentityMismatch();
    }
    return {
      text: 'This is a scripted fixture reply so the composer can be tested.',
      releaseId,
      disclaimer: DISCLAIMER,
    };
  }
}
