import { describe, expect, it } from 'vitest';
import { DisabledAdapter } from '../src/inference/DisabledAdapter';
import { MockAdapter } from '../src/inference/MockAdapter';
import { GenerationUnavailable, IdentityMismatch } from '../src/inference/types';

describe('DisabledAdapter', () => {
  it('refuses generation', async () => {
    const adapter = new DisabledAdapter();
    const caps = await adapter.capabilities();
    expect(caps.available).toBe(false);
    expect(caps.mock).toBe(false);
    await expect(adapter.generate()).rejects.toBeInstanceOf(GenerationUnavailable);
  });
});

describe('MockAdapter', () => {
  it('rejects a mismatched release identity', async () => {
    const adapter = new MockAdapter(true);
    await expect(
      adapter.generate({
        releaseId: 'fixture-base',
        mode: 'completion',
        prompt: 'hi',
      }),
    ).rejects.toBeInstanceOf(IdentityMismatch);
  });

  it('labels mock output', async () => {
    const adapter = new MockAdapter();
    const response = await adapter.generate({
      releaseId: 'fixture-base',
      mode: 'completion',
      prompt: 'hi',
    });
    expect(response.disclaimer).toMatch(/not generated by a released/i);
    expect(response.releaseId).toBe('fixture-base');
  });
});
